feat: subgraph integration
Vault-Hill/vhc-marketplace-server pull request #16
Opened 2022-03-09 16:22 UTC by jmulq

This goes alongside the following updates to the subgraph:
- https://github.com/Vault-Hill/vhc-marketplace-subgraph/pull/5

2022-03-10 04:48 UTC, anjorinjnr requested changes
This enough code that certain components should have unit tests, lets discuss that if you need help.

2022-03-10 04:48 UTC, anjorinjnr commented on src/services/subgraph.service/subgraph.service.ts
> +      // TODO: Add error logging
this todo is redundant, when you console.log[error] you are indeed logging. we can replace console.log with something more sophisticated to log object with properties etc but this is already logging stuff and it's fine for now.

2022-03-10 04:48 UTC, anjorinjnr commented on src/services/subgraph.service/types.ts
> +export type CollectionVland = {
we should discuss this types. i don't understand the difference between collectionvland and subgraphvland, perhaps you can add some comments to the types

2022-03-10 04:48 UTC, anjorinjnr commented on src/services/subgraph.service/query.ts
> +export const collectionQuery = `
collectionByAddressQuery?

2022-03-10 04:48 UTC, anjorinjnr commented on src/application.ts
> +    // Validate env variables
why is this repeated?

2022-03-10 04:48 UTC, anjorinjnr commented on package.json
> +    "@types/faker": "^6.6.9",
we can remove this.

2022-03-10 04:48 UTC, anjorinjnr commented on src/repositories/asset.repository.ts
> +  implements LifeCycleObserver
remove the implements

2022-03-10 04:48 UTC, anjorinjnr commented on src/repositories/asset.repository.ts
> +  start() {}
remove both methods

2022-03-10 04:48 UTC, anjorinjnr commented on src/services/subgraph.service/subgraph.service.ts
> +      const collections: Collection[] = []
the buildCollection is specifically about vLand, so unless there can be multiple vland collections am not sure why we have this for loop.

2022-03-10 04:48 UTC, anjorinjnr commented on src/services/subgraph.service/subgraph.service.ts
> +      const response = await fetch(uri)
we are gonna run into latency issues if every request involves

app -> server -> graph       -> app
                         -> ipfs fetch

good to idea to open an issue to revisit this later

2022-03-10 04:48 UTC, anjorinjnr commented on src/application.ts
> +const ENV_VARS = ['SUBGRAPH_API_URL']
do/will we have dev instance of the subgraph vs prod.  please provide url of the instance you're using for test.

2022-03-10 22:40 UTC, jmulq commented on src/repositories/asset.repository.ts
> +  start() {}
Removed from asset and collection repo

2022-03-10 22:40 UTC, jmulq commented on src/repositories/asset.repository.ts
> +  implements LifeCycleObserver
Removed implements. Presume it's also good to remove the lifecycle observer decorator?

2022-03-10 22:48 UTC, jmulq commented on src/application.ts
> +const ENV_VARS = ['SUBGRAPH_API_URL']
https://api.thegraph.com/subgraphs/name/vault-hill/vhc-marketplace dev version.

we should have one for dev, one for staging, and one for prod I would say.

2022-03-10 22:50 UTC, jmulq commented on src/services/subgraph.service/subgraph.service.ts
> +      // TODO: Add error logging
Remove in latest PR. Logger ticket for future enhancement -> https://github.com/Vault-Hill/vhc-marketplace-server/issues/18

2022-03-10 22:51 UTC, jmulq commented on src/services/subgraph.service/types.ts
> +export type CollectionVland = {
Have made the types for explanatory. They were worded badly beforehand.

The subgraph types are the `Collection` and `Vland` types coming from the subgraph.

The metadata type is the vland metadata stored on IPFS.

2022-03-10 22:51 UTC, jmulq commented on src/services/subgraph.service/query.ts
> +export const collectionQuery = `
Good shout - changed this.

2022-03-10 22:52 UTC, jmulq commented on src/application.ts
> +    // Validate env variables
Just to be doubly sure we validate the env.

2022-03-10 22:52 UTC, jmulq commented on src/application.ts
> +    // Validate env variables
jk, removed in latest push

2022-03-10 22:53 UTC, jmulq commented on src/services/subgraph.service/subgraph.service.ts
> +      const collections: Collection[] = []
Good point. Changed it in latest push. Still returns an array, just without the loop. Can update when more collections come in.

2022-03-10 22:54 UTC, jmulq commented on src/services/subgraph.service/subgraph.service.ts
> +      const response = await fetch(uri)
Raised to eng tracker and added issue here https://github.com/Vault-Hill/vhc-marketplace-server/issues/19

2022-03-10 23:40 UTC, anjorinjnr submitted a review, later dismissed

2022-03-11 12:38 UTC, abbeydabiri approved these changes

2022-03-11 14:37 UTC, merged