feat: buy now creation
Vault-Hill/vhc-marketplace-server pull request #21
Opened 2022-03-24 15:08 UTC by jmulq

This PR includes buy now creation logic, and updating the datasource to mongodb.

There is a subgraph PR that goes alongside this - https://github.com/Vault-Hill/vhc-marketplace-subgraph/pull/9

2022-03-24 15:35 UTC, anjorinjnr requested changes
this is look mostly good.

since there's no unit/integration test yet, have you provisioned a test/staging db and did you test with that?

2022-03-24 15:35 UTC, anjorinjnr commented on src/graphql-types/asset.ts
> +  // TODO: Add Auction type when implemented
do you intend to add a separate property for auctions here?

2022-03-24 15:35 UTC, anjorinjnr commented on src/repositories/buy-now.repository.ts
> +    const buyNow: Partial<BuyNow> = {
can there be muutiple active buynow orders for an asset?

2022-03-24 17:05 UTC, jmulq commented on src/graphql-types/asset.ts
> +  // TODO: Add Auction type when implemented
My plan was to make the type be one of `BuyNow` or `Auction`. That way there can only be on active listing, that is one of those two types.

2022-03-24 17:06 UTC, jmulq commented on src/repositories/buy-now.repository.ts
> +    const buyNow: Partial<BuyNow> = {
No. Once a buy now has been created for an asset, no further buy nows should be able to be created with our solution.

2022-03-24 20:03 UTC, anjorinjnr commented on src/repositories/buy-now.repository.ts
> +    const buyNow: Partial<BuyNow> = {
that's what I thought so you should probably add a validation here.

2022-03-24 20:27 UTC, anjorinjnr commented on src/graphql-types/asset.ts
> +  // TODO: Add Auction type when implemented
Ok. So to resolve the field, you will have to run two queries BuyNow and Auction? Perhaps you can use a single collection to represent both?

2022-03-24 20:28 UTC, anjorinjnr reviewed
See comments

2022-03-24 22:55 UTC, jmulq commented on src/repositories/buy-now.repository.ts
> +    const buyNow: Partial<BuyNow> = {
Added validation to the resolver. See latest commit

2022-03-24 22:56 UTC, jmulq commented on src/graphql-types/asset.ts
> +  // TODO: Add Auction type when implemented
Have created a `Listing` entity now that will represent both. See latest commit.

2022-03-24 23:36 UTC, anjorinjnr commented on src/graphql-types/asset.ts
> +  // TODO: Add Auction type when implemented
lgtm

2022-03-24 23:38 UTC, anjorinjnr requested changes
lgtm

please run lint:fix and squash the commits.

2022-03-25 13:37 UTC, anjorinjnr approved these changes
lgtm see minot comment

2022-03-25 13:37 UTC, anjorinjnr commented on src/graphql-types/asset.ts
> +  activeListing?: Listing
should this just be `listing`? the associated listing may not always be active right?

2022-03-25 13:38 UTC, anjorinjnr commented
Also pls add dev values in the .env example, so someone can actually checkout the code and run it.

2022-03-25 16:20 UTC, jmulq commented on src/graphql-types/asset.ts
> +  activeListing?: Listing
I was thinking that an associated `Listing` would always be active. i.e. when a listing is cancelled or finished, we set this field to null.

2022-03-25 16:58 UTC, anjorinjnr submitted a review, later dismissed

2022-03-28 12:19 UTC, merged