WIP: implement cancel buy now
Vault-Hill/vhc-marketplace-server pull request #25
Opened 2022-04-01 12:01 UTC by jmulq

Currently WIP - unit tests are being written.

Added cancel buy now mutation

Update assets resolver to return listing associated with each asset - currently this was only added to the single asset query.

2022-04-05 23:50 UTC, anjorinjnr requested changes

2022-04-05 23:50 UTC, anjorinjnr commented on src/graphql-resolvers/asset-resolver.ts
> +    for (const vland of vlands) {
this is going to run N db queries, it's not efficient.  replace with something like

```ts
this.listingRepo.find({
  where: {
    assetId: {
      inq: vlands.map(v => v.tokenId.toString())
    },
    {
      assetAddress: {
        inq: vlands.map(v => v.tokenAddress)
      }
   }
 }
 })
```
then use the results to associate the listings

2022-04-05 23:50 UTC, anjorinjnr commented on src/graphql-resolvers/listing-resolver.ts
> +    const { assetId, assetAddress } = data
move all this logic into the repository

2022-04-06 10:43 UTC, jmulq commented on src/graphql-resolvers/asset-resolver.ts
> +    for (const vland of vlands) {
Good shout - I need to start using these filter options more. 

Have changed in latest commit.

2022-04-06 10:44 UTC, jmulq commented on src/graphql-resolvers/listing-resolver.ts
> +    const { assetId, assetAddress } = data
Have moved it over. Why should this logic sit in the repository instead of the mutation? 

Should the other methods in the listing resolver have the majority of their logic also moved over to the repository?

2022-04-06 10:45 UTC, jmulq commented
Added PR comments commit - will rebase and fixup once finalised PR

2022-04-06 13:51 UTC, anjorinjnr requested changes

2022-04-06 13:51 UTC, anjorinjnr commented on src/graphql-resolvers/asset-resolver.ts
> +    for (const vland of vlands) {
you can replace       

```ts
    const vlandListings = await this.listingRepo.find({
      where: {
        assetId: {
          inq: vlands.map((vland) => vland.tokenId.toString())
        },
        assetAddress: {
          inq: vlands.map((vland) => vland.tokenAddress)
        }
      }
    })
```
with this more efficient code
```ts
    const vlandListings = keyBy(await this.listingRepo.find({
      where: {
        assetId: {
          inq: vlands.map((vland) => vland.tokenId.toString())
        },
        assetAddress: {
          inq: vlands.map((vland) => vland.tokenAddress)
        }
      }
    }), 'assetId')

return vlands.map(vland => {
    vland.listing = vlandListings[vland.tokenId.toString())
   return vland
})
```

2022-04-06 13:51 UTC, anjorinjnr commented on src/graphql-resolvers/listing-resolver.ts
> +    const { assetId, assetAddress } = data
Ideally this kind of logic should be in a service, but putting then in the repo makes it easier to reuse and keeps the resolvers light. Resolvers are like controllers and shouldn't have too much biz logic.

2022-04-06 13:51 UTC, anjorinjnr commented on src/repositories/listing.repository.ts
> +  async cancelListing(assetId: string, assetAddress: string) {
this can just be `cancel`

2022-04-06 14:17 UTC, anjorinjnr requested changes
so actually I think this needs some additional changes.

an asset can have multiple listings, so the getListing in asset() resolver should be getCurrentListing and the logic changed to something like

```ts
  return this.findOne({ 
      where: { assetAddress, assetId }, 
      order: 'createdAt DESC' 
  })
```

similarly the assets() resolver need to be updated to something like
```ts
const vlandListings = groupBy(
    await this.listingRepo.find({
         where: {
            assetId: { inq: vlands.map((vland) => vland.tokenId.toString()) }, 
            assetAddress: { inq: vlands.map((vland) => vland.tokenAddress) } 
          }, 
         order: 'createdAt DESC' 
     }), 'assetId')

 return vlands.map(vland => {
     vland.listing = vlandListings[vland.tokenId.toString())[0]
     return vland 
})


```

2022-04-07 16:27 UTC, anjorinjnr approved these changes
lgtm

2022-04-08 01:42 UTC, anjorinjnr commented
@jmulq  there were issues with your last refactor commit - did you test it before pushing the change?

I've made the updates but until you add the test, please do manual test to make sure your changes are good

2022-04-08 01:42 UTC, merged