fix: refactor listing model and repo to calculate status
Vault-Hill/vhc-marketplace-server pull request #74
Opened 2022-05-06 19:43 UTC by jmulq

This fixes the issue where a buy now listing can be unlisted or purchase after it has exceeded the end date.

2022-05-06 20:00 UTC, creativogee submitted a review, later dismissed

2022-05-09 12:45 UTC, anjorinjnr requested changes

2022-05-09 12:45 UTC, anjorinjnr commented on src/graphql-types/listing.ts
> +  public isActive() {
I think you want to make to make this getter fields, so they can be available in the response to the client

2022-05-09 13:18 UTC, jmulq commented on src/graphql-types/listing.ts
> +  public isActive() {
Made this and the other two getters fields. Is this needed or shall we just limit it to the `isActive` field?

Changes committed to PR comments. Once approved will rebase and fixup the commit.

2022-05-09 18:59 UTC, anjorinjnr submitted a review, later dismissed

2022-05-09 21:23 UTC, merged

2022-05-09 21:23 UTC, jmulq commented
Resolved conflicts - rebasing as previously approved.