feat: gbp usd tracking
Vault-Hill/vhc-marketplace-server pull request #76
Opened 2022-05-10 16:53 UTC by jmulq

The purpose of these changes, is so that we can keep track of the amount of currency spent to fill a listing.

The total amount is the set value, the fees are the total minus the 1.5% fee paid by the purchaser of the NFT, and the amount minus fees are the remainder that goes to the listing creator. It is required that we keep a GBP/USD conversion of our sales.

2022-05-10 18:03 UTC, anjorinjnr commented on src/graphql-types/bid.ts
> +  @field((type) => Price)
are there fees on bid?

2022-05-10 18:03 UTC, anjorinjnr commented on src/graphql-types/fillPriceData.ts
> +@objectType({ description: 'Amount for a asset' })
what is this object for?

2022-05-10 18:06 UTC, jmulq commented on src/graphql-types/bid.ts
> +  @field((type) => Price)
yeah - in the sense that a bid is just a 0x order waiting to be filled, and the bidder will pay a fee of 1.5% to VH, similar to a buy now listing.

2022-05-10 18:09 UTC, jmulq commented
> you can just have a fillAmount field in the listing object
> 
> ```ts
> {
>   amount: Price
>   fee: Price
>   netAmount: Price
>   usdRate: number
>   gbpRate: number
> }
> ```

Where net amount is the amount minus fees? Or with fees (i.e. the total)

Is the usdRate and gbpRate just the rate of the chosen currency at the time? So 1 VHC in USD/GBP, and then we can do any calculations we need to at a later date?

2022-05-10 18:13 UTC, anjorinjnr commented on src/graphql-types/bid.ts
> +  @field((type) => Price)
but why do you need the information on the bid?
The fees only apply when  the bid is accepted and a txn is created

2022-05-10 18:13 UTC, anjorinjnr commented on src/services/currency-exchange.service.ts/currency-exchange.service.ts
> +@injectable({ scope: BindingScope.TRANSIENT })
you really could just make this a simple function

2022-05-16 16:46 UTC, jmulq commented on src/graphql-types/listing.ts
> +  priceData: FillAmount
Good point. Have updated this in latest changes.

2022-05-16 16:47 UTC, jmulq commented on src/services/currency-exchange.service.ts/currency-exchange.service.ts
> +@injectable({ scope: BindingScope.TRANSIENT })
Made into a helper func in changes

2022-05-16 16:51 UTC, anjorinjnr commented on .github/workflows/deploy-prod.yaml
>    DB_URL: ${{ secrets.MARKETPLACE_PROD_DB_URL }}
change to MARKETPLACE_DB_URL_PROD

2022-05-16 16:52 UTC, anjorinjnr commented on .github/workflows/deploy-prod.yaml
>    SUBGRAPH_API_URL: ${{ secrets.PROD_SUBGRAPH_API }}
change to SUBGRAPH_API_PROD

2022-05-16 16:52 UTC, anjorinjnr commented on .github/workflows/deploy-prod.yaml
> +  PRIVATE_KEY: ${{ secrets.MKT_PRIVATE_KEY }}
MARKETPLACE_PRIVATE_KEY_PROD

2022-05-16 16:53 UTC, anjorinjnr requested changes
naming consistency

2022-05-16 17:02 UTC, jmulq commented
> naming consistency

Just updated these following comments

2022-05-16 17:02 UTC, anjorinjnr approved these changes

2022-05-16 17:04 UTC, merged